lint.gradle.test: fix test classpath order
These are Lint CLI tests, thus CLI deps should come first. Without
this change, tests fail with IntelliJ 2025.1:

  java.lang.NoSuchMethodError:
  ...PsiFileEx.isBatchReferenceProcessingEnabled

Probably the Studio IDE deps should be removed altogether, but this
will be investigated separately. The immediate priority is to unblock
the IntelliJ 2025.1 update.

See also: Change I49f97ae43.

Change-Id: I0457a048d2308cceb68e914d5f144662164e94e5