Fix Guava version crash in ResourceType
Modified ResourceType.java to use Guava methods compatible with
older versions. This prevents a NoSuchMethodError on
Sets.toImmutableEnumSet by using Collectors.toCollection
and Sets.immutableEnumSet instead, which are available in
older Guava releases.

This resolves issues where layoutlib-api, a dependency of the
screenshot testing plugin, caused crashes in projects
with older Guava versions on the classpath.

Bug: 429990486
Test: Existing & Manual testing
Change-Id: I0c7fa40a9f02ff1330694ba38546e630e7bf6ba9